### ISSUE TITLE
how skip eac

### ISSUE THREAD

**Issue by Yirss** [arturzxc/grinder#4]
I have never played games on Linux, May I ask how it evades the detection of EAC.

**Comment by danytrol** [comment]
> Я никогда не играл в игры на Linux, могу я спросить, как это позволяет избежать обнаружения EAC?

As I understand it in Linux OS, EAC does not get superuser rights and runs on limited capabilities. In Windows, you give administrator rights without any choice.
And it also seems to me just too lazy to refine the anti-cheat for Linux OS, that's all. Since the steam platform develops Linux and games in it (steam deck) and EAC rolled out a raw version of the anti-cheat, but it will end soon

**Comment by Yirss** [comment]
thanks, today I will try it out
